trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
- name: BuildPlatform
  value : 'any cpu'
- name: BuildConfiguration
  value: 'release'

pool:
  workspace:
    clean: all
  name: 'DAS - Continuous Integration'

resources:
  repositories:
    - repository: das-platform-building-blocks
      type: github
      name: SkillsFundingAgency/das-platform-building-blocks
      ref: refs/heads/master
      endpoint: 'GitHub (SFA)'

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
